version: '3.1'
services:
  redmine:
    image: redmine
    restart: always
    ports: 
      - 3000:3000
    environment:
      REDMINE_DB_POSTGRES: mine-postgres
      REDMINE_DB_PASSWORD: 1234
      REDMINE_DB_USERNAME: redmine

  mine-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: redmine

